// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isudxjkhndgggzfuvtec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzdWR4amtobmRnZ2d6ZnV2dGVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NTg5MzAsImV4cCI6MjA2MDUzNDkzMH0.kfsqdem06rpF69z8OL_rlfV6hmQ0Bh7YCURKk_ToQiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);